services:
  - type: web
    name: flask-pedidos
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      # Puedes agregar más variables aquí